FROM ubuntu:latest

#setting the working directore
WORKDIR /app

#copying python script to the /app folder in the base Image
COPY pythonScript.py /app

RUN apt-get update && apt-get install -y python3 python3-pip

CMD ["python3", "pythonScript.py"]
